server:
  port: 8080
spring:
  cloud:
    config:
      enabled: false
  application:
    name: plazoleta-service
  datasource:
    url: jdbc:mysql://localhost:3306/db_plazoleta
    username: root
    password: Password
  jpa:
    hibernate:
      ddl-auto: update
security:
  jwt:
    secret: ${JWT_SECRET:clavesecretaparamicroserviciosdeplazoletadedecomidas}
    expiration-minutes: 120
usuarios:
  service:
    url: http://localhost:8081
mensajeria:
  service:
    url: http://localhost:8083/api/v1/notifications/sms
  apikey: dev-secret