server:
  port: ${PORT_PLAZOLETA}

spring:
  cloud:
    config:
      enabled: false
  application:
    name: plazoleta-service
  datasource:
    url: ${URL_DB_RESTAURANTES}
    username: ${USERNAME_DB}
    password: ${PASSWORD_DB}
  jpa:
    hibernate:
      ddl-auto: update

security:
  jwt:
    secret: ${JWT_SECRET}
    expiration-minutes: 120

usuarios:
  service:
    url: ${URL_SERVICE_USER}

mensajeria:
  service:
    url: ${URL_SERVICE_MENSAJERIA}
  apikey: ${API_KEY_MENSAJERIA}

trazabilidad:
  service:
    url: ${URL_SERVICE_TRAZABILIDAD}
  internal-token: ${INTERNAL_TOKEN_TRAZABILIDAD}
